export const COMPONENT = Object.freeze({
  CONTACT_US_FORM: 'contact-us-form',
  MEDIA_ENQUIRY_FORM: 'media-enquiry-form',
  OUR_OFFICES: 'our-offices',
  QUICK_LINKS: 'quick-links',
  INVESTOR_CONTACTS: 'investor-contacts-container',
  BREADCRUMBS: 'breadcrumbs',
  JOB_VACANCIES: 'job-vacancies',
  HOME_BANNER: 'home-Banner',
  CONTENT_CAROUSEL: 'content-carousel',
  TABS: 'tabs',
  FEATURED_PROPERTIES: 'featured-properties',
  INTERESTING_FACTS_CARD: 'interestingfactscard',
  INFO_NO_GRAPH: 'infonograph',
  HOME_BANNER_CAROUSEL: 'home-banner-carousel',
  TESTIMONIALS_CAROUSEL: 'testimonials-carousel',
  FEATURED_PROPERTIES_CAROUSEL: 'features-properties-carousel',
  CUSTOM_CAROUSEL:'custom-carousel',
});
