export class User {
  UserId: number | undefined;
  RoleId: number | undefined;
  ProvinceId: number | undefined;
  FirstName: string | undefined;
  LastName: string | undefined;
  CompanyName: string | undefined;
  CellNumber: string | undefined;
  OfficeNumber: string | undefined;
  Email: string | undefined;
  VerifiedAt: string | undefined;
  Dob: string | undefined;
  Sector: string | undefined;
  SectorId: string | undefined;
  Areas: string | undefined;
  PersonalInterest: string | undefined;
  SubscriptionPreferences: string | undefined;
  IsDeleted: number | undefined;
  Status: number | undefined;
  ApproveStatus: number | undefined;
  Reason: string | undefined;
  CreatedOn: string | undefined;
  UpdatedOn: string | undefined;
}
