export const colors = [
  {
    name: 'Deep red',
    code: '#aa0015',
    class: 'rd-text-deep-red',
    bgClass: 'rd-bg__deep-red',
    borderClass: 'rd-border__deep-red',
  },
  {
    name: 'Dominant red',
    code: '#c00018',
    class: 'rd-text-dominant-red',
    bgClass: 'rd-bg__dominant-red',
    borderClass: 'rd-border__dominant-red',
  },
  {
    name: 'Mid red',
    code: '#ce171e',
    class: 'rd-text-mid-red',
    bgClass: 'rd-bg__mid-red',
    borderClass: 'rd-border__mid-red',
  },
  {
    name: 'Red',
    code: '#e6001c',
    class: 'rd-text-red',
    bgClass: 'rd-bg__red',
    borderClass: 'rd-border__red',
  },
  {
    name: 'Bright green',
    code: '#78c36c',
    class: 'rd-text-bright-green',
    bgClass: 'rd-bg__bright-green',
    borderClass: 'rd-border__bright-green',
  },
  {
    name: 'Teal light',
    code: '#289889',
    class: 'rd-text-teal-light',
    bgClass: 'rd-bg__teal-light',
    borderClass: 'rd-border__teal-light',
  },
  {
    name: 'Teal dark',
    code: '#017d67',
    class: 'rd-text-teal-dark',
    bgClass: 'rd-bg__teal-dark',
    borderClass: 'rd-border__teal-dark',
  },

  {
    name: 'Teal purple',
    code: '#555d8b',
    class: 'rd-text-teal-purple',
    bgClass: 'rd-bg__teal-purple',
    borderClass: 'rd-border__teal-purple',
  },

  {
    name: 'Black',
    code: '#000000',
    class: 'rd-text-black',
    bgClass: 'rd-bg__black',
    borderClass: 'rd-border__black',
  },
  {
    name: 'Grey dark',
    code: '#333333',
    class: 'rd-text-grey-dark',
    bgClass: 'rd-bg__grey-dark',
    borderClass: 'rd-border__grey-dark',
  },
  {
    name: 'Grey',
    code: '#58595b',
    class: 'rd-text-grey',
    bgClass: 'rd-bg__grey',
    borderClass: 'rd-border__grey',
  },
  {
    name: 'Grey mid',
    code: '#999999',
    class: 'rd-text-grey-mid',
    bgClass: 'rd-bg__grey-mid',
    borderClass: 'rd-border__grey-mid',
  },
  {
    name: 'Grey light',
    code: '#cccccc',
    class: 'rd-text-grey-light',
    bgClass: 'rd-bg__grey-light',
    borderClass: 'rd-border__grey-light',
  },
  {
    name: 'Grey very light',
    code: '#f9f9f9',
    class: 'rd-text-grey-very-light',
    bgClass: 'rd-bg__grey-very-light',
    borderClass: 'rd-border__grey-very-light',
  },
  {
    name: 'Neutral grey',
    code: '#f9fafb',
    class: 'rd-text-neutral-grey',
    bgClass: 'rd-bg__neutral-grey',
    borderClass: 'rd-border__neutral-grey',
  },
  {
    name: 'White',
    code: '#ffffff',
    class: 'rd-text-white',
    bgClass: 'rd-bg__white',
    borderClass: 'rd-border__white',
  },
  {
    name: 'Orange bright',
    code: '#f58220',
    class: 'rd-text-orange-bright',
    bgClass: 'rd-bg__orange-bright',
    borderClass: 'rd-border__orange-bright',
  },

  {
    name: 'Turquoise',
    code: '#68c9d0',
    class: 'rd-text-turquoise',
    bgClass: 'rd-bg__turquoise',
    borderClass: 'rd-border__turquoise',
  },
  {
    name: 'Turquoise mid',
    code: '#00718d',
    class: 'rd-text-turquoise-mid',
    bgClass: 'rd-bg__turquoise-mid',
    borderClass: 'rd-border__turquoise-mid',
  },
  {
    name: 'Turquoise dark',
    code: '#004b6a',
    class: 'rd-text-turquoise-dark',
    bgClass: 'rd-bg__turquoise-dark',
    borderClass: 'rd-border__turquoise-dark',
  },
  {
    name: 'Mist',
    code: '#bcc9c1',
    class: 'rd-text-mist',
    bgClass: 'rd-bg__mist',
    borderClass: 'rd-border__mist',
  },
  {
    name: 'Nude',
    code: '#e3ddd2',
    class: 'rd-text-nude',
    bgClass: 'rd-bg__nude',
    borderClass: 'rd-border__nude',
  },
  {
    name: 'Sky blue',
    code: '#7cbcd9',
    class: 'rd-text-sky-blue',
    bgClass: 'rd-bg__sky-blue',
    borderClass: 'rd-border__sky-blue',
  },
  {
    name: 'Orange',
    code: '#efb270',
    class: 'rd-text-orange',
    bgClass: 'rd-bg__orange',
    borderClass: 'rd-border__orange',
  },
  {
    name: 'Purple',
    code: '#8d83a6',
    class: 'rd-text-purple',
    bgClass: 'rd-bg__purple',
    borderClass: 'rd-border__purple',
  },
  {
    name: 'Secondary leaf',
    code: '#75b897',
    class: 'rd-text-secondary-leaf',
    bgClass: 'rd-bg__secondary-leaf',
    borderClass: 'rd-border__secondary-leaf',
  },
  {
    name: 'Industrial grey',
    code: '#5c676d',
    class: 'rd-text-industrial-grey',
    bgClass: 'rd-bg__industrial-grey',
    borderClass: 'rd-border__industrial-grey',
  },
];
